# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  ollama-server:
    image: ollama/ollama
    container_name: ollama-server
    ports:
      - ${LLM_ENDPOINT_PORT:-8008}:11434
    environment:
      LLM_MODEL_ID: "qwen3:4b"
      host_ip: host.docker.internal

networks:
  default:
    driver: bridge